package-lock.json, package.json, scripts/setup.js
- pre-commit is only required for those contributing and our internal team, this repo is used in our sample code download functionality where pre-commit hooks are not required so I am removing it from `postinstall` npm script.
=> change husky npm script from postinstall

packages/read-and-create-calendar-events/client/react/package.json, packages/read-and-create-calendar-events/server/node-express/package.json, packages/read-and-create-calendar-events/server/node-express/server.js, packages/read-emails/client/react/package.json, packages/read-emails/server/node-express/package-lock.json, packages/read-emails/server/node-express/package.json, packages/read-emails/server/node-express/server.js, packages/read-emails/server/node/package.json, packages/read-emails/server/node/server.js, packages/send-and-read-emails/client/react/package.json, packages/send-and-read-emails/server/node-express/package.json, packages/send-and-read-emails/server/node-express/server.js, packages/send-and-read-emails/server/node/package.json, packages/send-and-read-emails/server/node/server.js, packages/send-emails/server/node-express/server.js, packages/send-emails/server/node/server.js, scripts/start.js
- allow configurable client port via `PORT=3002 npm run start`
- fix `clientUri` key in `ServerBindings.express` options
=> fix ServerBindings.express in all server.js samples

packages/send-and-read-emails/client/react/src/App.js, packages/send-and-read-emails/server/node-express/route.js, packages/send-and-read-emails/server/node/route.js
- Returns only 5 threads, instead of 50, for `send-and-read-emails` use case
- Added `key` prop to `DisplayEmail` component to remove the warning `Each child in a list should have a unique "key" prop.` in App.js for ReadEmails
=> [send-and-read-emails] return only five threads

packages/send-and-read-emails/client/react/src/App.js
- Refactored `App.js`, so it doesn't call `handleTokenExchange()` more than once
- Moved updating of URL with `userId` to its own `useEffect` hook
- Removed duplicate `setUserId` invocation
=> [send-and-read-emails] Double webhook events when connecting an account

packages/read-emails/client/react/src/App.js
- Refactored `App.js`, so it doesn't call `handleTokenExchange()` more than once
- Moved updating of URL with `userId` to its own `useEffect` hook
- Removed duplicate `setUserId` invocation
=> [read-emails] Double webhook events when connecting an account

packages/read-and-create-calendar-events/client/react/src/App.js
- Refactored `App.js`, so it doesn't call `handleTokenExchange()` more than once
- Moved updating of URL with `userId` to its own `useEffect` hook
- Removed duplicate `setUserId` invocation
=> [read and create calendar events] Double webhook events when connecting an account

packages/send-emails/client/react/src/App.js
- Refactored `App.js`, so it doesn't call `handleTokenExchange()` more than once
- Moved updating of URL with `userId` to its own `useEffect` hook
- Removed duplicate `setUserId` invocation
=> [send-emails] Double webhook events when connecting an account

packages/read-and-create-calendar-events/server/node-express/server.js, packages/read-and-create-calendar-events/server/node-express/utils/formatting.js, packages/read-emails/server/node-express/server.js, packages/read-emails/server/node-express/utils/formatting.js, packages/read-emails/server/node/server.js, packages/read-emails/server/node/utils/formatting.js, packages/send-and-read-emails/server/node-express/server.js, packages/send-and-read-emails/server/node-express/utils/index.js, packages/send-and-read-emails/server/node/server.js, packages/send-and-read-emails/server/node/utils/index.js, packages/send-emails/server/node-express/server.js, packages/send-emails/server/node-express/utils/formatting.js, packages/send-emails/server/node/server.js, packages/send-emails/server/node/utils/formatting.js
- replace `prettyPrintJSON(value)` with `JSON.stringify(value, undefined, 2)` in `backend/server.js` for each use-case
- remove `prettyPrintJSON` from `utils` directors
=> remove `prettyPrintJSON` dependency from code snippets

packages/read-and-create-calendar-events/client/react/src/App.js, packages/read-and-create-calendar-events/client/react/src/utils/date.js, packages/read-and-create-calendar-events/server/node-express/package.json, packages/read-and-create-calendar-events/server/node-express/route.js
- You should be able to only view calendar events from your primary calendar. 
- The start and end date times should be in your computer’s timezone
- Only your most recent calendar events should be displayed
- Only return top 5 events within a +7 day range
https://nylas.atlassian.net/browse/TEM-120
=> Fixed incorrect data being populated for calendar usecase

packages/read-and-create-calendar-events/client/react/src/App.js, packages/read-emails/client/vue/src/App.vue, packages/send-emails/client/react/src/App.js
Remove `handleTokenExchange` function and made it inline to avoid context switch for our users so that it is easier to follow as you go through the steps
For templates we need to keep it as simple as possible for our users, so don’t need to have best practices here
=> Remove handleTokenExchange function and make it inline to avoid context switch

.gitignore, packages/send-and-read-emails/client/react/src/App.js, packages/send-and-read-emails/server/node-express/route.js, packages/send-and-read-emails/server/node-express/server.js, packages/send-and-read-emails/server/node-express/utils/mock-db.js, packages/send-and-read-emails/server/node/route.js, packages/send-and-read-emails/server/node/server.js, packages/send-and-read-emails/server/node/utils/mock-db.js
- Fixed the issue where refreshing the store resulted in loss of connected account
- Added a local file db system to replace existing mock db which stores the account info locally
=> [read-and-send-email]: Fixed refreshing page after connecting an account results in a loss of connected account info

packages/read-emails/client/react/src/App.js, packages/read-emails/server/node-express/server.js, packages/read-emails/server/node-express/utils/mock-db.js, packages/read-emails/server/node/server.js, packages/read-emails/server/node/utils/mock-db.js
- Fixed the issue where refreshing the store resulted in loss of connected account
- Added a local file db system to replace existing mock db which stores the account info locally
=> [read-emails]: Fix refreshing page losing connected account info

packages/send-emails/client/react/src/App.js, packages/send-emails/server/node-express/server.js, packages/send-emails/server/node-express/utils/mock-db.js, packages/send-emails/server/node/server.js, packages/send-emails/server/node/utils/mock-db.js
- Fixed the issue where refreshing the store resulted in loss of connected account
- Added a local file db system to replace existing mock db which stores the account info locally
=> [send-emails]: Fixed refreshing page resulting in loss of connected account info issue

packages/read-emails/frontend/react/src/App.jsx
- Added a check for `userId` being  falsey, so `exchangeCodeFromUrlForToken()` isn't called twice
=> [read emails] regression - Double webhook events when connecting an account

packages/read-and-create-calendar-events/backend/node-express/server.js, packages/read-emails/backend/node-express/package-lock.json, packages/read-emails/backend/node-express/server.js, packages/read-emails/backend/node/server.js, packages/send-and-read-emails/backend/node-express/server.js, packages/send-and-read-emails/backend/node/server.js, packages/send-emails/backend/node-express/server.js, packages/send-emails/backend/node/server.js
Update server code for all use cases to use an environment variable for the local client server URL (`CLIENT_URI`), with a fall back default of `localhost:PORT` when the environment variable is not configured
=> [all use-cases] update middleware an environment variable for local client server URI

packages/read-and-create-calendar-events/frontend/react/src/CalendarClient.jsx, packages/read-and-create-calendar-events/frontend/react/src/index.jsx, packages/read-emails/frontend/react/src/App.jsx, packages/read-emails/frontend/react/src/index.jsx, packages/send-and-read-emails/frontend/react/src/index.jsx, packages/send-emails/frontend/react/src/index.jsx
Update react client code for all use cases to use an environment variable for the local backend server URL (SERVER_URI), with a fall back default of `localhost:PORT` when the environment variable is not configured
=> [all use cases] update all react code to use an environment variable for the local api server url

packages/read-emails/frontend/vue/package.json
`scripts/start.js` fails to serve vue frontend for read-emails use-case.
Updated npm run script command for vue from `npm run serve` to `npm run start` to match call from `scripts/start.js` for react frontends.
=> [read-email] update npm command for vue frontend

packages/read-and-create-calendar-events/frontend/react/src/utils/date.js
Fixes issue with Nylas API receiving invalid time between 12:00am and 12:59am.
Turns out `en-CA` locale defaults to a `h24` cycle (01:00 to 24:59) instead of the assumed `h23` cycle (0:00 to 23:59).  Passing the `{ hourCycle: 'h23' }` parameter fixes this issue.
=> [Sample Calendar App] Fix invalid date bug

packages/read-and-create-calendar-events/backend/node-express/route.js, packages/read-and-create-calendar-events/frontend/react/src/App.jsx, packages/read-and-create-calendar-events/frontend/react/src/CreateEventForm.jsx, packages/read-and-create-calendar-events/frontend/react/src/NylasLogin.jsx, packages/read-and-create-calendar-events/frontend/react/src/styles/calendar.scss, packages/read-and-create-calendar-events/frontend/react/src/utils/date.js
Provides default start and end times in the `Create Event` form.
- `startTime` defaults to next half hour interval (i.e.`:00 or :30`)
- `endTime` defaults to one hour after default start time
- Set minimum `endTime` to `startTime + 1 minute`. (API calls where `startTime === endTime` fail)
- Removed unused date functions.
- Adds `userId` to `sessionStorage` to match Email Sample App
- moved preparing `participants` array to the backend
=> [Calendar Sample App] Add Default Start and End Times to Create Event

packages/read-orders/frontend/react/src/OrderApp.jsx
Fixes divider line displaying over top of "No available orders" when no orders were found.
=> [read-orders] remove panel divider when no orders are found

packages/read-and-create-calendar-events/frontend/react/src/CreateEventForm.jsx, packages/read-and-create-calendar-events/frontend/react/src/utils/date.js
Looks like we relied upon re-building an ISO string to do a UTC -> local time conversion. This conversion didn't always work.
=> Using strings to convert date time was not working as expected

packages/read-and-create-calendar-events/frontend/react/src/styles/style.scss, packages/send-and-read-emails/frontend/react/src/styles/style.scss, packages/send-emails/frontend/react/src/styles/style.scss
Webkit specific CSS is causing a flicker for the toast notification
https://user-images.githubusercontent.com/314152/218853689-79fca673-f040-45fb-ba19-99f9e2ab286e.mp4
https://user-images.githubusercontent.com/314152/218872557-1852e8b7-2f96-4b43-b82c-16f95a10d8d5.mp4
=> CSS animation timing causes toast to flicker

packages/read-and-create-calendar-events/backend/java/build.gradle, packages/read-and-create-calendar-events/backend/java/src/main/java/Server.java, packages/read-emails/backend/java/build.gradle, packages/read-emails/backend/java/src/main/java/Server.java, packages/send-and-read-emails/backend/java/build.gradle, packages/send-and-read-emails/backend/java/src/main/java/Server.java, packages/send-emails/backend/java/build.gradle, packages/send-emails/backend/java/src/main/java/Server.java
Upgrade all the Java apps to use the v1.21.0 Java SDK and use the new toJSON() method instead of using GSON to serialize the models.
```js
```
=> Update to Java SDK v1.21.0 and use new toJSON method

packages/read-and-create-calendar-events/frontend/react/src/components/Toast.jsx, packages/read-and-create-calendar-events/frontend/react/src/styles/style.scss, packages/send-and-read-emails/frontend/react/src/components/Layout.jsx, packages/send-and-read-emails/frontend/react/src/components/Toast.jsx, packages/send-and-read-emails/frontend/react/src/styles/style.scss, packages/send-emails/frontend/react/src/components/Toast.jsx, packages/send-emails/frontend/react/src/styles/style.scss
<p align="center">
</p>
<p align="center">
</p>
=> [All Guides] Toast Fixes (Flicker and Min-Width

packages/read-emails/backend/java/src/main/java/Server.java, packages/read-emails/backend/node/server.js, packages/read-emails/backend/python/server.py, packages/read-emails/backend/ruby/server.rb, packages/send-and-read-emails/backend/java/src/main/java/Server.java, packages/send-and-read-emails/backend/node/server.js, packages/send-and-read-emails/backend/python/server.py, packages/send-and-read-emails/backend/ruby/server.rb, packages/send-emails/backend/java/src/main/java/Server.java
Some of the scopes being requested were too granular and not included in our Sandbox app Google Verification process. Using these scopes lead to users getting an "App Blocked" error by google.
We're updating the code to use the more "permissive" scopes (e.g. email.read_only -> email.modify) to avoid having the user run into any auth errors while testing these sample apps.
=> Fixed scopes to work with Sandbox Apps
