nylas/use-cases

- packages/send-and-read-emails/client/react/package-lock.json
- scripts/setup.js
- adds prompts for client id and client secret in `setup` script
`npm run setup`
https://user-images.githubusercontent.com/34139730/184981259-5e7ee52d-f633-45db-a201-2167923bfb1e.mov
> add prompts for client id and secret

- scripts/setup.js
- scripts/start.js
Supports the following setups by running `npm run setup`:
`setupSourceRepo`
```
packages/
read-emails/
client/
react
html
server/
node
node-express
```
`setupDownloadedRepo`
```
src/
client/
server/
```
> update setup script for downloaded repos

- .github/workflows/pull-request.yml
- README.md
- package-lock.json
- package.json
- scripts/setup.js
- `npm install && npm run start`
> add npm run setup to postinstall

- README.md
- package-lock.json
- package.json
- packages/read-emails/client/vue/package-lock.json
- packages/read-emails/client/vue/package.json
- packages/read-emails/client/vue/public/index.html
- packages/read-emails/client/vue/src/App.vue
- packages/read-emails/client/vue/src/main.js
- packages/read-emails/client/vue/vue.config.js
This PR adds Vue support for read emails use cases. Functionally it works but the styling is a bit off.
> Create vue demo for read-email use case

- packages/send-and-read-emails/client/react/src/App.js
- Removed extra console.log in `sendEmail()`
> [send-and-read-emails] Duplicate logging when a message is sent

- packages/read-and-create-calendar-events/server/node-express/server.js
- packages/read-emails/server/node-express/server.js
- packages/read-emails/server/node/server.js
- packages/send-and-read-emails/server/node-express/server.js
- packages/send-and-read-emails/server/node/server.js
- packages/send-emails/server/node-express/server.js
- packages/send-emails/server/node/server.js
- Removed check for dev env around webhook bindings in all `server.js` files
> [all use-cases] Dev env check wrapping webhook bindings

- packages/read-emails/client/react/package-lock.json
- packages/read-emails/server/node-express/server.js
> refactor read emails server file

- packages/read-emails/client/react/src/App.js
- packages/read-emails/client/react/src/Email.js
- packages/read-emails/client/react/src/EmailList.js
- packages/read-emails/client/react/src/styles.js
> read emails: refactor client react code

- packages/send-and-read-emails/server/node-express/package-lock.json
- packages/send-and-read-emails/server/node-express/route.js
- packages/send-and-read-emails/server/node-express/server.js
> send-read-emails: refactor server code

- packages/send-and-read-emails/client/react/package-lock.json
- packages/send-and-read-emails/client/react/src/App.js
- packages/send-and-read-emails/client/react/src/EmailClient.js
- packages/send-and-read-emails/client/react/src/ReadEmails.js
- packages/send-and-read-emails/client/react/src/SendEmails.js
- packages/send-and-read-emails/client/react/src/styles.js
- packages/send-and-read-emails/server/node-express/server.js
- packages/send-and-read-emails/server/node/package-lock.json
- packages/send-and-read-emails/server/node/route.js
- packages/send-and-read-emails/server/node/server.js
> [use-cases] update send read emails code snippets

- .eslintrc.cjs
- package-lock.json
- package.json
- packages/read-and-create-calendar-events/server/node-express/server.js
- packages/read-emails/client/vue/package-lock.json
- packages/read-emails/server/node/package-lock.json
- packages/read-emails/server/node/server.js
- packages/send-and-read-emails/server/node-express/server.js
- packages/send-and-read-emails/server/node/server.js
- packages/send-emails/server/node-express/server.js
- packages/send-emails/server/node/server.js
- scripts/setup.js
- scripts/start.js
- will help prevent horizontal scaling as much as possible in the code explorer on dashboard
> add eslint max-len to 80

- packages/send-emails/server/node-express/server.js
- packages/send-emails/server/node/server.js
> [send-email] refactor server code

- packages/read-emails/client/react/src/App.js
- packages/send-emails/client/react/src/App.js
- packages/send-emails/client/react/src/EmailClient.js
- packages/send-emails/client/react/src/SendEmails.js
- packages/send-emails/client/react/src/styles.js
- packages/send-emails/server/node-express/server.js
- packages/send-emails/server/node/server.js
> [send-emails] refactor send emails client

- SETUP.md
- adds a setup.md file for downloaded sample apps. README.md will be excluded when sample apps are downloaded from the dashboard.
> setup.md for download sample apps

- packages/read-and-create-calendar-events/client/react/package-lock.json
- packages/read-and-create-calendar-events/server/node-express/package-lock.json
- packages/read-and-create-calendar-events/server/node-express/route.js
- packages/read-and-create-calendar-events/server/node-express/server.js
- packages/send-and-read-emails/server/node-express/route.js
- packages/send-and-read-emails/server/node-express/server.js
- re-arrange calendar events server code to make an easier read.
> [calendar-events] refactor server code

- packages/read-and-create-calendar-events/server/node-express/package.json
- packages/read-emails/server/node-express/package.json
- packages/read-emails/server/node/package-lock.json
- packages/read-emails/server/node/package.json
- packages/send-and-read-emails/server/node-express/package.json
- packages/send-and-read-emails/server/node/package.json
- packages/send-emails/server/node-express/package.json
- packages/send-emails/server/node/package.json
> [use-cases] update nylas-js dependency to beta

- .eslintrc.cjs
- package-lock.json
- packages/read-emails/frontend/react/package-lock.json
- packages/read-emails/frontend/react/src/App.jsx
- packages/read-emails/frontend/react/src/components/Layout.jsx
- packages/read-emails/frontend/react/src/styles/base.scss
- packages/read-emails/frontend/react/src/styles/style.scss
- Add disconnect account button and its functions
- Update `userId` to session storage so refresh page won't logout user
- This PR is based off https://github.com/nylas/use-cases/pull/60
> Add disconnect account button and its functions

- packages/read-emails/frontend/react/src/App.jsx
- packages/read-emails/frontend/react/src/Email.jsx
- packages/read-emails/frontend/react/src/EmailList.jsx
- packages/read-emails/frontend/react/src/EmailPreview.jsx
- packages/read-emails/frontend/react/src/components/Layout.jsx
- packages/read-emails/frontend/react/src/styles/email.scss
- packages/read-emails/frontend/react/src/styles/style.scss
- Added scrollable email list 
- Created new component `EmailPreview` and updated style for email preview item
- Extract Email sample app in a new component
- This PR is based of https://github.com/nylas/use-cases/pull/61
> [Email sample app] Added email list and email preview items

- packages/read-emails/backend/node-express/server.js
- packages/read-emails/backend/node/server.js
- packages/read-emails/frontend/react/src/App.jsx
- packages/read-emails/frontend/react/src/EmailApp.jsx
- packages/read-emails/frontend/react/src/EmailDetail.jsx
- packages/read-emails/frontend/react/src/EmailList.jsx
- packages/read-emails/frontend/react/src/EmailPreview.jsx
- packages/read-emails/frontend/react/src/styles/email.scss
- Updated Email sample app thread view to show each email as threads
- Thread will be collapsed with more than 4 messages 
- Loading message body on demand, only loads when clicking on the email message
- Added selected state of thread in thread list
- Added loading state when loading email body
> Email sample app thread view

- packages/read-and-create-calendar-events/frontend/react/src/App.jsx
Filter out cancelled events (currently showing as duplicates).
> [Calendar Sample App] Filter out cancelled events from frontend

- packages/schedule-events/frontend/react/src/App.jsx
- Moves useEffect so both highlighting blocks appear in view for the "manage user access tokens" step
> [schedule-events] move `useEffect`

- packages/read-emails/backend/node/package.json
- packages/send-and-read-emails/backend/node/package.json
- scripts/setup.js
- scripts/start.js
> feat(scripts): add ruby support

- packages/read-and-create-calendar-events/backend/node/server.js
- packages/send-and-read-emails/backend/node/server.js
- packages/send-emails/backend/node/server.js
> refactor(node): docs changes

- packages/read-and-create-calendar-events/backend/python/server.py
- packages/read-emails/backend/python/server.py
- packages/send-and-read-emails/backend/python/server.py
- packages/send-emails/backend/python/server.py
> docs(python): clean up

- packages/read-and-create-calendar-events/frontend/react/package-lock.json
- packages/read-and-create-calendar-events/frontend/react/package.json
Was missing luxon and dompurify, causing crash on start.
> Added missing deps.

- SETUP.md
- packages/read-and-create-calendar-events/backend/node/README.md
- packages/read-and-create-calendar-events/backend/python/README.md
- packages/read-and-create-calendar-events/frontend/react/README.md
- packages/read-emails/backend/node/README.md
- packages/read-emails/backend/python/README.md
- packages/read-emails/frontend/react/README.md
- packages/read-orders/backend/node/README.md
- packages/read-orders/frontend/react/README.md
- packages/schedule-events/backend/node/README.md
- packages/schedule-events/frontend/react/README.md
- packages/send-and-read-emails/backend/node/README.md
- packages/send-and-read-emails/backend/python/README.md
- packages/send-and-read-emails/frontend/react/README.md
- packages/send-emails/backend/node/README.md
- packages/send-emails/backend/python/README.md
- packages/send-emails/frontend/react/README.md
Copy edits on the SETUP file. :)
> Cull the SETUP instructions so they're not confusing to readers.

- .gitignore
- README.md
- packages/read-and-create-calendar-events/backend/java/README.md
- packages/read-and-create-calendar-events/backend/node/README.md
- packages/read-and-create-calendar-events/backend/python/README.md
- packages/read-and-create-calendar-events/backend/ruby/README.md
- packages/read-and-create-calendar-events/frontend/react/README.md
- packages/read-emails/backend/java/README.md
- packages/read-emails/backend/node/README.md
- packages/read-emails/backend/python/README.md
- packages/read-emails/backend/ruby/README.md
- packages/read-emails/frontend/react/README.md
- packages/read-orders/backend/node/README.md
- packages/read-orders/frontend/react/README.md
- packages/schedule-events/backend/node/README.md
- packages/schedule-events/frontend/react/README.md
- packages/send-and-read-emails/backend/java/README.md
- packages/send-and-read-emails/backend/node/README.md
- packages/send-and-read-emails/backend/python/README.md
- packages/send-and-read-emails/backend/ruby/README.md
- packages/send-and-read-emails/frontend/react/README.md
- packages/send-emails/backend/java/README.md
- packages/send-emails/backend/node/README.md
- packages/send-emails/backend/python/README.md
- packages/send-emails/backend/ruby/README.md
- packages/send-emails/frontend/react/README.md
Expands, clarifies, and standardizes the READMEs for the samples.
> Readme improvements

- SETUP.md
Small copy edit. Nylas is an adjective modifying the tool.
> Enforce styleguide

- packages/read-and-create-calendar-events/frontend/react/src/CreateEventForm.jsx
- ensure start and end time are displayed correctly on UI
- denote required fields for create event
```js
```
> Update read-and-create-calendar-events frontend
